-- 無法使用 DBMS_METADATA 嘗試內部產生器轉換物件 FFX.FFXDS_BANK 的 TABLE DDL.
ALTER TABLE FFX.FFXDS_BANK
ADD CONSTRAINT UK_FFXDS_BANK UNIQUE 
(
  BANK_CODE 
)
USING INDEX FFX.UK_FFXDS_BANK
ENABLECREATE TABLE FFX.FFXDS_BANK 
(
  FFXDS_BANK_ID NUMBER(19, 0) DEFAULT FFX.SEQ_FFXDS_BANK.nextval 
, OPT_LOCK NUMBER(10, 0) 
, BANK_CODE VARCHAR2(11 BYTE) 
, RELATION_CODE VARCHAR2(1 BYTE) 
, POSTAGE_CODE VARCHAR2(1 BYTE) 
, NMADR1 VARCHAR2(35 BYTE) 
, NMADR2 VARCHAR2(35 BYTE) 
, NMADR3 VARCHAR2(35 BYTE) 
, NMADR4 VARCHAR2(35 BYTE) 
, NMADR5 VARCHAR2(35 BYTE) 
, POBOX VARCHAR2(20 BYTE) 
, TELEX_NO VARCHAR2(20 BYTE) 
, CITY_NO VARCHAR2(7 BYTE) 
, DP_NAME VARCHAR2(15 BYTE) 
, CHIPS_NO VARCHAR2(6 BYTE) 
, RISK_COUNTRY_CODE VARCHAR2(2 BYTE) 
, FATCA_FLAG VARCHAR2(1 BYTE) 
, RATING_FLAG VARCHAR2(1 BYTE) 
, RATING_DATE VARCHAR2(8 BYTE) 
, CONTROL_MARK VARCHAR2(1 BYTE) 
, RANK NUMBER(3, 0) DEFAULT 0 
, DELETE_YM VARCHAR2(6 BYTE) 
, TRANS_BANK_CODE VARCHAR2(11 BYTE) 
, COUNTRY_NO VARCHAR2(4 BYTE) 
, VOSTRO_STATUS VARCHAR2(1 BYTE) 
, VOSTRO_EFFECTIVE_DATE VARCHAR2(8 BYTE) 
, CABLE_NO NVARCHAR2(23) 
, TX_DATE TIMESTAMP(6) WITH TIME ZONE 
) 
LOGGING 
TABLESPACE FFX_DS_DATA_TS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLELCOMMENT ON COLUMN FFX.FFXDS_BANK.FFXDS_BANK_ID IS 'id';
COMMENT ON COLUMN FFX.FFXDS_BANK.OPT_LOCK IS 'OPT_LOCK';
COMMENT ON COLUMN FFX.FFXDS_BANK.BANK_CODE IS '銀行BIC代碼';
COMMENT ON COLUMN FFX.FFXDS_BANK.RELATION_CODE IS '與本行關係代號';
COMMENT ON COLUMN FFX.FFXDS_BANK.POSTAGE_CODE IS '郵電費率代號';
COMMENT ON COLUMN FFX.FFXDS_BANK.NMADR1 IS '銀行全名   REF :FOE21200代收銀行';
COMMENT ON COLUMN FFX.FFXDS_BANK.NMADR2 IS '銀行全名';
COMMENT ON COLUMN FFX.FFXDS_BANK.NMADR3 IS '名稱地址三';
COMMENT ON COLUMN FFX.FFXDS_BANK.NMADR4 IS '名稱地址四';
COMMENT ON COLUMN FFX.FFXDS_BANK.NMADR5 IS '名稱地址五';
COMMENT ON COLUMN FFX.FFXDS_BANK.POBOX IS '郵箱號碼';
COMMENT ON COLUMN FFX.FFXDS_BANK.TELEX_NO IS 'TELEX 號碼';
COMMENT ON COLUMN FFX.FFXDS_BANK.CITY_NO IS '都市代號';
COMMENT ON COLUMN FFX.FFXDS_BANK.DP_NAME IS '簡稱';
COMMENT ON COLUMN FFX.FFXDS_BANK.CHIPS_NO IS '美元跨境清算系統編號';
COMMENT ON COLUMN FFX.FFXDS_BANK.RISK_COUNTRY_CODE IS '最終風險國別';
COMMENT ON COLUMN FFX.FFXDS_BANK.FATCA_FLAG IS '是否為FATCA';
COMMENT ON COLUMN FFX.FFXDS_BANK.RATING_FLAG IS '高/中/低風險';
COMMENT ON COLUMN FFX.FFXDS_BANK.RATING_DATE IS '重估風險日';
COMMENT ON COLUMN FFX.FFXDS_BANK.CONTROL_MARK IS '管制記號';
COMMENT ON COLUMN FFX.FFXDS_BANK.RANK IS '世界排名';
COMMENT ON COLUMN FFX.FFXDS_BANK.DELETE_YM IS '取消日期';
COMMENT ON COLUMN FFX.FFXDS_BANK.TRANS_BANK_CODE IS '已移轉至新BANK CODE';
COMMENT ON COLUMN FFX.FFXDS_BANK.COUNTRY_NO IS '國家代號';
COMMENT ON COLUMN FFX.FFXDS_BANK.VOSTRO_STATUS IS '同存資料狀態';
COMMENT ON COLUMN FFX.FFXDS_BANK.VOSTRO_EFFECTIVE_DATE IS '同存生效日';
COMMENT ON COLUMN FFX.FFXDS_BANK.CABLE_NO IS 'CABLE 號碼';
COMMENT ON COLUMN FFX.FFXDS_BANK.TX_DATE IS '交易日期/時間';COMMENT ON TABLE FFX.FFXDS_BANK IS '銀行檔'CREATE UNIQUE INDEX FFX.UK_FFXDS_BANK ON FFX.FFXDS_BANK (BANK_CODE ASC) 
LOGGING 
TABLESPACE FFX_DS_DATA_TS 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
